package src.organisation;

public enum InformationsTypes {
    GAMEMODE , GAMEBOARD ,LOGIN, CONNECTIONSTATUS, MESSAGE, CREATEACCOUNT, ERROR, SUCESS, START, PROMOTION, TIMEOUT, WIN, LOSS,DRAW, REMOVE
}
